server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-route
              uri: lb://account-service
              predicates:
                - Path=/accounts/**
            - id: transaction-route
              uri: lb://transaction-service
              predicates:
                - Path=/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

gateway:
  secret-token: ${GATEWAY_SECRET_TOKEN}
